import Head from 'next/head'
import Image from 'next/image'
import Agrements from '../Components/Sections/Home/Agrements/Agrements'
import Banner from '../Components/Sections/Home/Banner/Banner'
import Domaines from '../Components/Sections/Home/Domaines/Domaines'
import InfoBanner from '../Components/Sections/Home/InfoBanner/InfoBanner'
import Sectors from '../Components/Sections/Home/Sectors/Sectors'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Security</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Banner/>
        <InfoBanner/>
        <Domaines/>
        <Sectors/>
        <Agrements/>
      </main>
    </div>
  )
}
